version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: fulltime-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
